class ImageResolver {
  static String resolveWeatherIcon(String weatherValue) {
    switch (weatherValue) {
      case "1":
        return "image/weather/01.svg";
      case "2":
        return "image/weather/02.svg";
      case "3":
        return "image/weather/03.svg";
      case "4":
        return "image/weather/04.svg";
      case "5":
        return "image/weather/05.svg";
      case "6":
        return "image/weather/06.svg";
      case "7":
        return "image/weather/07.svg";
      case "8":
        return "image/weather/08.svg";
      case "9":
        return "image/weather/08.svg";
      case "10":
        return "image/weather/08.svg";
      case "11":
        return "image/weather/08.svg";
      case "12":
        return "image/weather/08.svg";
      case "13":
        return "image/weather/08.svg";
      case "14":
        return "image/weather/08.svg";
      case "15":
        return "image/weather/08.svg";
      case "16":
        return "image/weather/08.svg";
      case "17":
        return "image/weather/08.svg";
      case "18":
        return "image/weather/09.svg";
      case "19":
        return "image/weather/09.svg";
      case "20":
        return "image/weather/10.svg";
      case "21":
        return "image/weather/10.svg";
      case "22":
        return "image/weather/11.svg";
      case "23":
        return "image/weather/11.svg";
      case "24":
        return "image/weather/11.svg";
      case "25":
        return "image/weather/11.svg";
      case "26":
        return "image/weather/11.svg";
      case "27":
        return "image/weather/11.svg";
      case "28":
        return "image/weather/12.svg";
      case "29":
        return "image/weather/12.svg";
      case "30":
        return "image/weather/12.svg";
      case "31":
        return "image/weather/12.svg";
      case "32":
        return "image/weather/13.svg";
      case "33":
        return "image/weather/13.svg";
      case "34":
        return "image/weather/13.svg";
      case "35":
        return "image/weather/14.svg";
      case "36":
        return "image/weather/14.svg";
      case "37":
        return "image/weather/14.svg";
      case "38":
        return "image/weather/14.svg";
      case "39":
        return "image/weather/14.svg";
      case "40":
        return "image/weather/14.svg";
      case "41":
        return "image/weather/14.svg";
      case "42":
        return "image/weather/15.svg";
      case "43":
        return "image/weather/15.svg";
      case "44":
        return "image/weather/15.svg";
      case "45":
        return "image/weather/15.svg";
      case "46":
        return "image/weather/15.svg";
      case "47":
        return "image/weather/15.svg";
      case "48":
        return "image/weather/15.svg";
      case "49":
        return "image/weather/15.svg";
      case "50":
        return "image/weather/15.svg";
      case "51":
        return "image/weather/15.svg";
      case "52":
        return "image/weather/15.svg";
      case "53":
        return "image/weather/16.svg";
      case "54":
        return "image/weather/16.svg";
      case "55":
        return "image/weather/16.svg";
      case "56":
        return "image/weather/16.svg";
      case "57":
        return "image/weather/16.svg";
      case "58":
        return "image/weather/16.svg";
      case "59":
        return "image/weather/16.svg";
      case "60":
        return "image/weather/17.svg";
      case "61":
        return "image/weather/18.svg";
      case "62":
        return "image/weather/19.svg";
      case "63":
        return "image/weather/20.svg";
      case "64":
        return "image/weather/21.svg";
      case "65":
        return "image/weather/22.svg";
      case "66":
        return "image/weather/22.svg";
      case "67":
        return "image/weather/22.svg";
      case "68":
        return "image/weather/22.svg";
      case "69":
        return "image/weather/22.svg";
      case "70":
        return "image/weather/22.svg";
      case "71":
        return "image/weather/22.svg";
      case "72":
        return "image/weather/22.svg";
      case "73":
        return "image/weather/22.svg";
      case "74":
        return "image/weather/22.svg";
      case "75":
        return "image/weather/22.svg";
      case "76":
        return "image/weather/22.svg";
      case "77":
        return "image/weather/22.svg";
      case "78":
        return "image/weather/22.svg";
      case "79":
        return "image/weather/22.svg";
      case "80":
        return "image/weather/22.svg";
      case "81":
        return "image/weather/22.svg";
      case "82":
        return "image/weather/22.svg";
      case "83":
        return "image/weather/23.svg";
      case "84":
        return "image/weather/23.svg";
      case "85":
        return "image/weather/23.svg";
      case "86":
        return "image/weather/23.svg";
      case "87":
        return "image/weather/23.svg";
      case "88":
        return "image/weather/23.svg";
      case "89":
        return "image/weather/23.svg";
      case "90":
        return "image/weather/23.svg";
      case "91":
        return "image/weather/23.svg";
      case "92":
        return "image/weather/23.svg";
      case "93":
        return "image/weather/23.svg";
      case "94":
        return "image/weather/23.svg";
      case "95":
        return "image/weather/23.svg";
      case "96":
        return "image/weather/23.svg";
      case "97":
        return "image/weather/24.svg";
      case "98":
        return "image/weather/24.svg";
      case "99":
        return "image/weather/24.svg";
      case "100":
        return "image/weather/24.svg";
      case "101":
        return "image/weather/24.svg";
      case "102":
        return "image/weather/24.svg";
      case "103":
        return "image/weather/24.svg";
      case "104":
        return "image/weather/24.svg";
      case "105":
        return "image/weather/24.svg";
      case "106":
        return "image/weather/24.svg";
      case "107":
        return "image/weather/25.svg";
      case "108":
        return "image/weather/25.svg";
      case "109":
        return "image/weather/25.svg";
      case "110":
        return "image/weather/25.svg";
      case "111":
        return "image/weather/25.svg";
      case "112":
        return "image/weather/25.svg";
      case "113":
        return "image/weather/25.svg";
      case "114":
        return "image/weather/25.svg";
      case "115":
        return "image/weather/25.svg";
      case "116":
        return "image/weather/25.svg";
      case "117":
        return "image/weather/25.svg";
      case "118":
        return "image/weather/25.svg";
      case "119":
        return "image/weather/25.svg";
      case "120":
        return "image/weather/25.svg";
      case "121":
        return "image/weather/25.svg";
      case "122":
        return "image/weather/25.svg";
      case "123":
        return "image/weather/26.svg";
      case "124":
        return "image/weather/26.svg";
      case "125":
        return "image/weather/26.svg";
      case "126":
        return "image/weather/26.svg";
      case "127":
        return "image/weather/26.svg";
      case "128":
        return "image/weather/26.svg";
      case "129":
        return "image/weather/26.svg";
      case "130":
        return "image/weather/26.svg";
      case "131":
        return "image/weather/26.svg";
      case "132":
        return "image/weather/26.svg";
      case "133":
        return "image/weather/26.svg";
      case "134":
        return "image/weather/26.svg";
      case "135":
        return "image/weather/26.svg";
      case "136":
        return "image/weather/27.svg";
      case "137":
        return "image/weather/27.svg";
      case "138":
        return "image/weather/27.svg";
      case "139":
        return "image/weather/27.svg";
      case "140":
        return "image/weather/27.svg";
      case "141":
        return "image/weather/27.svg";
      case "142":
        return "image/weather/27.svg";
      case "143":
        return "image/weather/27.svg";
      case "144":
        return "image/weather/27.svg";
      case "145":
        return "image/weather/27.svg";
      case "146":
        return "image/weather/27.svg";
      case "147":
        return "image/weather/27.svg";
      case "148":
        return "image/weather/27.svg";
      case "149":
        return "image/weather/27.svg";
      case "150":
        return "image/weather/27.svg";
      case "151":
        return "image/weather/27.svg";
      case "152":
        return "image/weather/27.svg";
      case "153":
        return "image/weather/27.svg";
      case "154":
        return "image/weather/27.svg";
      case "155":
        return "image/weather/27.svg";
      case "156":
        return "image/weather/27.svg";
      case "157":
        return "image/weather/27.svg";
      case "158":
        return "image/weather/27.svg";
      case "159":
        return "image/weather/27.svg";
      case "160":
        return "image/weather/27.svg";
      case "161":
        return "image/weather/27.svg";
      case "162":
        return "image/weather/27.svg";
      case "163":
        return "image/weather/27.svg";
      case "164":
        return "image/weather/27.svg";
      case "165":
        return "image/weather/27.svg";
      case "166":
        return "image/weather/27.svg";
      case "167":
        return "image/weather/27.svg";
      case "168":
        return "image/weather/27.svg";
      case "169":
        return "image/weather/27.svg";
      case "170":
        return "image/weather/27.svg";
      case "171":
        return "image/weather/27.svg";
      case "172":
        return "image/weather/27.svg";
      case "173":
        return "image/weather/27.svg";
      case "174":
        return "image/weather/28.svg";
      case "175":
        return "image/weather/28.svg";
      case "176":
        return "image/weather/29.svg";
      case "177":
        return "image/weather/29.svg";
      case "178":
        return "image/weather/30.svg";
      case "179":
        return "image/weather/30.svg";
      case "180":
        return "image/weather/31.svg";
      case "181":
        return "image/weather/31.svg";
      case "182":
        return "image/weather/31.svg";
      case "183":
        return "image/weather/31.svg";
      case "184":
        return "image/weather/32.svg";
      case "185":
        return "image/weather/32.svg";
      case "186":
        return "image/weather/32.svg";
      case "187":
        return "image/weather/32.svg";
      case "188":
        return "image/weather/32.svg";
      case "189":
        return "image/weather/32.svg";
      case "190":
        return "image/weather/33.svg";
      case "191":
        return "image/weather/33.svg";
      case "192":
        return "image/weather/33.svg";
      case "193":
        return "image/weather/33.svg";
      case "194":
        return "image/weather/34.svg";
      case "195":
        return "image/weather/34.svg";
      case "196":
        return "image/weather/34.svg";
      case "197":
        return "image/weather/34.svg";
      case "198":
        return "image/weather/34.svg";
      case "199":
        return "image/weather/34.svg";
      case "200":
        return "image/weather/34.svg";
      case "201":
        return "image/weather/34.svg";
      case "202":
        return "image/weather/34.svg";
      case "203":
        return "image/weather/34.svg";
      case "204":
        return "image/weather/34.svg";
      case "205":
        return "image/weather/34.svg";
      case "206":
        return "image/weather/34.svg";
      case "207":
        return "image/weather/34.svg";
      case "208":
        return "image/weather/34.svg";
      case "209":
        return "image/weather/34.svg";
      case "210":
        return "image/weather/35.svg";
      case "211":
        return "image/weather/35.svg";
      case "212":
        return "image/weather/35.svg";
      case "213":
        return "image/weather/35.svg";
      case "214":
        return "image/weather/35.svg";
      case "215":
        return "image/weather/35.svg";
      case "216":
        return "image/weather/35.svg";
      case "217":
        return "image/weather/35.svg";
      case "218":
        return "image/weather/35.svg";
      case "219":
        return "image/weather/35.svg";
      case "220":
        return "image/weather/35.svg";
      case "221":
        return "image/weather/35.svg";
      case "222":
        return "image/weather/36.svg";
      case "223":
        return "image/weather/36.svg";
      case "224":
        return "image/weather/36.svg";
      case "225":
        return "image/weather/36.svg";
      case "226":
        return "image/weather/36.svg";
      case "227":
        return "image/weather/36.svg";
      case "228":
        return "image/weather/36.svg";
      case "229":
        return "image/weather/36.svg";
      case "230":
        return "image/weather/36.svg";
      case "231":
        return "image/weather/36.svg";
      case "232":
        return "image/weather/36.svg";
      case "233":
        return "image/weather/36.svg";
      case "234":
        return "image/weather/36.svg";
      case "235":
        return "image/weather/36.svg";
      case "236":
        return "image/weather/36.svg";
      case "237":
        return "image/weather/36.svg";
      case "238":
        return "image/weather/36.svg";
      case "239":
        return "image/weather/36.svg";
      case "240":
        return "image/weather/36.svg";
      case "241":
        return "image/weather/36.svg";
      case "242":
        return "image/weather/36.svg";
      case "243":
        return "image/weather/36.svg";
      case "244":
        return "image/weather/36.svg";
      case "245":
        return "image/weather/36.svg";
      case "246":
        return "image/weather/36.svg";
      case "247":
        return "image/weather/36.svg";
      case "248":
        return "image/weather/36.svg";
      case "249":
        return "image/weather/36.svg";
      case "250":
        return "image/weather/36.svg";
      case "251":
        return "image/weather/36.svg";
      case "252":
        return "image/weather/36.svg";
      case "253":
        return "image/weather/36.svg";
      case "254":
        return "image/weather/36.svg";
      case "255":
        return "image/weather/36.svg";
      case "256":
        return "image/weather/36.svg";
      case "257":
        return "image/weather/36.svg";
      case "258":
        return "image/weather/36.svg";
      case "259":
        return "image/weather/36.svg";
      case "260":
        return "image/weather/36.svg";
      case "261":
        return "image/weather/36.svg";
      case "262":
        return "image/weather/36.svg";
      case "263":
        return "image/weather/37.svg";
      case "264":
        return "image/weather/37.svg";
      case "265":
        return "image/weather/37.svg";
      case "266":
        return "image/weather/37.svg";
      case "267":
        return "image/weather/38.svg";
      case "268":
        return "image/weather/38.svg";
      case "269":
        return "image/weather/38.svg";
      case "270":
        return "image/weather/38.svg";
      case "271":
        return "image/weather/38.svg";
      case "272":
        return "image/weather/38.svg";
      case "273":
        return "image/weather/38.svg";
      case "274":
        return "image/weather/38.svg";
      case "275":
        return "image/weather/38.svg";
      case "276":
        return "image/weather/38.svg";
      case "277":
        return "image/weather/38.svg";
      case "278":
        return "image/weather/38.svg";
      case "279":
        return "image/weather/38.svg";
      case "280":
        return "image/weather/38.svg";
      case "281":
        return "image/weather/38.svg";
      case "282":
        return "image/weather/38.svg";
      case "283":
        return "image/weather/39.svg";
      case "284":
        return "image/weather/39.svg";
      case "285":
        return "image/weather/39.svg";
      case "286":
        return "image/weather/39.svg";
      case "287":
        return "image/weather/39.svg";
      case "288":
        return "image/weather/39.svg";
      case "289":
        return "image/weather/39.svg";
      case "290":
        return "image/weather/39.svg";
      case "291":
        return "image/weather/39.svg";
      case "292":
        return "image/weather/39.svg";
      case "293":
        return "image/weather/39.svg";
      case "294":
        return "image/weather/39.svg";
      case "295":
        return "image/weather/39.svg";
      case "296":
        return "image/weather/41.svg";
      case "297":
        return "image/weather/41.svg";
      case "298":
        return "image/weather/41.svg";
      case "299":
        return "image/weather/41.svg";
      case "300":
        return "image/weather/41.svg";
      case "301":
        return "image/weather/41.svg";
      case "302":
        return "image/weather/41.svg";
      case "303":
        return "image/weather/41.svg";
      case "304":
        return "image/weather/41.svg";
      case "305":
        return "image/weather/41.svg";
      case "306":
        return "image/weather/41.svg";
      case "307":
        return "image/weather/41.svg";
      case "308":
        return "image/weather/41.svg";
      case "309":
        return "image/weather/41.svg";
      case "310":
        return "image/weather/41.svg";
      case "311":
        return "image/weather/41.svg";
      case "312":
        return "image/weather/41.svg";
      case "313":
        return "image/weather/41.svg";
      case "314":
        return "image/weather/41.svg";
      case "315":
        return "image/weather/41.svg";
      case "316":
        return "image/weather/41.svg";
      case "317":
        return "image/weather/41.svg";
      case "318":
        return "image/weather/41.svg";
      case "319":
        return "image/weather/41.svg";
      case "320":
        return "image/weather/41.svg";
      case "321":
        return "image/weather/41.svg";
      case "322":
        return "image/weather/41.svg";
      case "323":
        return "image/weather/41.svg";
      case "324":
        return "image/weather/41.svg";
      case "325":
        return "image/weather/41.svg";
      case "326":
        return "image/weather/41.svg";
      case "327":
        return "image/weather/41.svg";
      case "328":
        return "image/weather/41.svg";
      case "329":
        return "image/weather/41.svg";
      case "330":
        return "image/weather/41.svg";
      case "331":
        return "image/weather/41.svg";
      case "332":
        return "image/weather/41.svg";
      case "333":
        return "image/weather/41.svg";
      case "334":
        return "image/weather/41.svg";
      case "335":
        return "image/weather/41.svg";
      case "336":
        return "image/weather/41.svg";
      case "337":
        return "image/weather/41.svg";
      case "338":
        return "image/weather/41.svg";
      case "339":
        return "image/weather/41.svg";
      default:
        return 'assets/icons/default.png'; // 預設圖片路徑，表示未知或無效的天氣狀況
    }
  }
}
